#!/usr/bin/env bash

cd "womens_courtyard"

printf "\e[33;1m%s\e[0m\n" 'Running unit tests'
flutter test --platform chrome
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" 'Unit tests error'
  exit 1
fi
printf "\e[33;1m%s\e[0m\n" 'Finished running unit tests'
