import 'package:mockito/annotations.dart';
import 'package:nivapp/item_spec.dart';
import 'package:nivapp/pickup_point.dart';
import 'package:nivapp/services/auth_service_i.dart';
import 'package:nivapp/services/init_service.dart';
import 'package:nivapp/services/inventory_service_i.dart';
import 'package:nivapp/services/report_service_i.dart';
import 'package:nivapp/services/routes_service_i.dart';

abstract class MyFunction {
  void call();
}

/// To generate mocks run in terminal:
/// ```
/// flutter pub run build_runner build --delete-conflicting-outputs web
/// ```
/// For every class ```A``` that is mocked, class ```MockA``` is generated by
/// the above command.
@GenerateMocks([
  Item,
  InventoryServiceI,
  ReportServiceI,
  RoutesServiceI,
  AuthServiceI,
  InitService,
  PickupPoint,
  MyFunction
])
void build_mocks_with_terminal() {}
